version: '3.7'
services:
  pentaho_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6589:8080"
    volumes:
      - pentaho_server_data:/home/pentaho/pentaho-server
      - pentaho_ext_data:/home/pentaho/pentaho-external-data
    container_name: pentaho_server
volumes:
  pentaho_server_data:
    driver_opts:
      type: none
      device: /home/pentaho_server/pentaho_server_data
      o: bind
  pentaho_ext_data:
    driver_opts:
      type: none
      device: /share/share/etl
      o: bind

